accum_steps: 1
batch_size: 128
checkpoint_epochs:
- 1
- 7
- 14
checkpointing_enabled: false
dataset_name: sun397
device: cuda
embed_dim: 512
head_artifact_ref: "adrianrob1-Sapienza Universit\xE0 di Roma/clip-finetune-sweeps/head_vit_base_patch16_clip_224.openai_sun397_seed42:latest"
head_source_loaded: wandb
lr: 9.865526573535462e-05
model_name: vit_base_patch16_224.openai_clip
momentum: null
n_total_params: 86193152
n_trainable_params: 85327872
num_classes: 397
optim: evon
optim_cfg_betas:
- 0.8
- 0.9999
optim_cfg_phasing: false
optim_cfg_ess: 500000000
optim_cfg_hess_init: 0.001
optim_cfg_lr: 9.865526573535462e-05
optim_cfg_mc_samples: 1
optim_cfg_precondition_1d: false
optim_cfg_price_clip_ratio: 2
optim_cfg_shampoo_beta: 0.995
optim_cfg_sync: false
optim_cfg_weight_decay: 5.213871057317842e-06
optim_cfg_whiten_prec_grad: true
optimizer_hparams:
  betas:
  - 0.8
  - 0.9999
  phasing: false
  ess: 500000000
  hess_init: 0.001
  lr: 9.865526573535462e-05
  mc_samples: 1
  precondition_1d: false
  price_clip_ratio: 2
  shampoo_beta: 0.995
  sync: false
  weight_decay: 5.213871057317842e-06
  whiten_prec_grad: true
physical_batch_size: 128
seed: 42
total_epochs: 14
trainable_scope: linear
wandb_project: clip-finetune-sweeps
weight_decay: 5.213871057317842e-06
